# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0a7476511328b50a8149f8f68356f0e3b303a0fed94d78108f145cce5050d202203f0d8a20d1eb5e866d317ed12055d616293292590d568a141fbe431120009

test:
  secret_key_base: 933cdb0275bea15b3c80e04b93bd9f05b8b07414296224c150267b2d8d5d6414c63731f608f14ad52fc5356ce72766f6eb3f8df333c82944e2806f4c914736cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
